### ISSUE TITLE
reinitialize tracker for same object

### ISSUE THREAD

**Issue by pritul2** [xl-sr/THOR#11]
I want to reinitialize the tracker which completely scan the image for the same object. If object is lost then tracker stays at the position where it lost, but if enters from some another side then tracker doesn't identify it. 

Is there any solution for that?

**Comment by pritul2** [comment]
Solved:-)

**Comment by samohadid** [comment]
Hi, If you are still alive after covid and everything happened in these two crazy years. how did you solve that issue. am facing the same issue.
