### ISSUE TITLE
get_test_data.sh is not found

### ISSUE THREAD

**Issue by ka10ryu1** [xl-sr/THOR#2]
https://github.com/xl-sr/THOR/blob/master/README.md#get-the-datasets

```
$ cd data
-bash: cd: data: No such file or directory
```
get_test_data.sh is not found.

**Comment by xl-sr** [comment]
try the instructions in the readme again, it should work now

**Comment by zlai0** [comment]
I also cannot find the download script get_test_data.sh. Is it provided?

**Comment by xl-sr** [comment]
yes, I added it

**Comment by zlai0** [comment]
Thanks!
