### ISSUE TITLE
Installation of oxuva==0.0.1

### ISSUE THREAD

**Issue by UndecidedBoy** [xl-sr/THOR#3]
Hello,

Quick questions: 
The Oxuva package in the file: **_environment.yml_** is supposed to be the long term tracking benchmark? Or is there another package with the same name? 
Also when executing the cmd **_pip install oxuva==0.0.1_**, I get an ERROR indicating that there is no matching distribution for oxuva. Do you have any clues on how to install the package and is the package mandatory for THOR?

Thank you for your time and consideration!

**Comment by xl-sr** [comment]
hey,

it is actually not necessary, I deleted it from the requirements. Thanks for noticing :)
