### ISSUE TITLE
Error on a CPU-only machine

### ISSUE THREAD

**Issue by stg101** [xl-sr/THOR#5]
```
RuntimeError: Attempting to deserialize object on a CUDA device but  torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use  torch.load with map_location='cpu' to map your storages to the CPU.  
```

According to the torch  [doc](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-across-devices) it is needed to provide a `map_location` when a gpu saved model is loaded on a cpu.

Changing [line 76](https://github.com/xl-sr/THOR/blob/681c201b7d7907df64799692d446c0503f1507a4/trackers/tracker.py#L76) in [trackers/tracker.py](https://github.com/xl-sr/THOR/blob/681c201b7d7907df64799692d446c0503f1507a4/trackers/tracker.py) solves the problem :

        model.load_state_dict(torch.load(model_path, map_location=('cpu'
                       if str(self.device) == 'cpu' else None)))

**Comment by xl-sr** [comment]
thanks! its updated now
